### PR TITLE
Workaround for 19.41 failed support

### PR DESCRIPTION
**Pull request by figueroa1395**
Local workaround for the failing Azure pipelines. 

Bug reported in https://github.com/conda-forge/vc-feedstock/issues/83

Workaround proposed in https://github.com/conda-forge/vc-feedstock/issues/83#issuecomment-2339943983

Since Azure images keep changing, according to https://github.com/conda-forge/vc-feedstock/issues/83#issuecomment-2340034565, the pipeline may still fail, but should run okay after some re-renders.

### CODE REVIEW

**Review by mgovers — APPROVED** [review]

**Review by mgovers — CHANGES_REQUESTED** [review]
base needs to be `main`

**Review by mgovers — APPROVED** [review]
I've updated the base branch

**Comment by mgovers** [comment]
@conda-forge-admin, please rerender

**Comment by figueroa1395** [comment]
@TonyXiang8787 the fix proposed here seems to fix (given some re-runs) the feedstock error. However, @mgovers and I realized that Travis CI is also failing (and has been since 19.30, we just hadn't noticed). Do you have any idea on what is going on here?

In addition, Travis CI was [run again](https://app.travis-ci.com/github/conda-forge/power-grid-model-feedstock/builds/272022479) on v1.9.28 of pgm (which is the last successful build) to check if we had introduced a problem, but it failed.

Additionally, this problem seems to be unrelated to the feedstock one, as before the re-render, all the CI jobs passed here, except Travis.

**Pull request closed without merging**
